/*
 * Copyright 2019 Wolfgang Reder.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package at.or.reder.rpi;

/**
 *
 * @author Wolfgang Reder
 */
public class EnergyPanel extends DevicePanel
{

  /**
   * Creates new form EnergyPanel
   */
  public EnergyPanel()
  {
    initComponents();
  }

//  @Override
//  public void setDevice(ZCAN device)
//  {
//    super.setDevice(device);
//    powerPanel1.setDevice(device);
//    powerControlPanel1.setDevice(device);
//    powerPanel2.setDevice(device);
//    powerControlPanel2.setDevice(device);
//  }
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
   * this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    powerPanel1.setLimitCurrent(5.0);
    powerPanel1.setLimitVoltage(15.0);
    powerPanel1.setMaxCurrent(6.0);
    powerPanel1.setMaxVoltage(20.0);
    powerPanel1.setPort(at.or.reder.zcan20.PowerPort.OUT_1);
    powerPanel1.setPowerMode(at.or.reder.zcan20.PowerMode.ON);

    powerPanel2.setLimitCurrent(3.0);
    powerPanel2.setLimitVoltage(15.0);
    powerPanel2.setMaxCurrent(6.0);
    powerPanel2.setMaxVoltage(20.0);
    powerPanel2.setPort(at.or.reder.zcan20.PowerPort.OUT_2);
    powerPanel2.setPowerMode(at.or.reder.zcan20.PowerMode.ON);

    powerControlPanel1.setPort(at.or.reder.zcan20.PowerPort.OUT_1);

    powerControlPanel2.setPort(at.or.reder.zcan20.PowerPort.OUT_2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(powerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(powerControlPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
        .addComponent(powerControlPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(powerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(powerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(powerPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(powerControlPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(powerControlPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18))
    );
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private final at.or.reder.rpi.PowerControlPanel powerControlPanel1 = new at.or.reder.rpi.PowerControlPanel();
  private final at.or.reder.rpi.PowerControlPanel powerControlPanel2 = new at.or.reder.rpi.PowerControlPanel();
  private final at.or.reder.rpi.PowerPanel powerPanel1 = new at.or.reder.rpi.PowerPanel();
  private final at.or.reder.rpi.PowerPanel powerPanel2 = new at.or.reder.rpi.PowerPanel();
  // End of variables declaration//GEN-END:variables
}
