/*
 * Copyright 2019 Wolfgang Reder.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package at.or.reder.rpi;

import at.or.reder.zcan20.LinkState;
import at.or.reder.zcan20.LinkStateListener;
import at.or.reder.zcan20.ZCAN;
import javax.swing.SwingUtilities;

/**
 *
 * @author Wolfgang Reder
 */
public class SettigsPanel extends DevicePanel
{

  private Runnable reconnectCallaback;
  private LinkStateListener linkStateListener;

  public SettigsPanel()
  {
    initComponents();

  }

  @Override
  protected void doLinkStateChanged(LinkState linkState)
  {
    setControlState();
  }

  private void onLickState(ZCAN can,
                           LinkState state)
  {
    SwingUtilities.invokeLater(this::setControlState);
  }

  @Override
  protected void connectListener()
  {
    if (device != null && linkStateListener == null) {
      linkStateListener = this::onLickState;
      device.addLinkStateListener(linkStateListener);
    }
  }

  @Override
  protected void disconnectListener()
  {
    if (linkStateListener != null && device != null) {
      device.removeLinkStateListener(linkStateListener);
    }
    linkStateListener = null;
  }

  public Runnable getReconnectCallaback()
  {
    return reconnectCallaback;
  }

  public void setReconnectCallaback(Runnable reconnectCallaback)
  {
    this.reconnectCallaback = reconnectCallaback;
  }

  private void setControlState()
  {
    btReconnect.setEnabled(device != null && device.getLinkState() != LinkState.OPEN && reconnectCallaback != null);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
   * this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    btReconnect.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
    btReconnect.setText(org.openide.util.NbBundle.getMessage(SettigsPanel.class, "SettigsPanel.btReconnect.text")); // NOI18N
    btReconnect.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btReconnectActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btReconnect)
        .addContainerGap(278, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btReconnect)
        .addContainerGap(257, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btReconnectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btReconnectActionPerformed
  {//GEN-HEADEREND:event_btReconnectActionPerformed
    if (reconnectCallaback != null) {
      reconnectCallaback.run();
    }
  }//GEN-LAST:event_btReconnectActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private final javax.swing.JButton btReconnect = new javax.swing.JButton();
  // End of variables declaration//GEN-END:variables
}
