/*
 * Copyright 2019 Wolfgang Reder.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package at.or.reder.rpi;

import at.or.reder.rpi.model.TrackElement;
import at.or.reder.rpi.model.impl.SpecialTrackElement;
import java.awt.Component;

/**
 *
 * @author Wolfgang Reder
 */
public final class APanel extends javax.swing.JPanel
{

  private final TrackElement teWGT = SpecialTrackElement.getWGT(null,
                                                                0);
  private final TrackElement teFHT = SpecialTrackElement.getFHT(null,
                                                                1);
  private final TrackElement teHAGT = SpecialTrackElement.getHAGT(null,
                                                                  2);
  private final TrackElement teSGT = SpecialTrackElement.getSGT(null,
                                                                2);

  public APanel()
  {
    initComponents();
    wgt.setElement(teWGT);
    fht.setElement(teFHT);
    hagt.setElement(teHAGT);
    sgt.setElement(teSGT);
  }

  private void fixCornerPoints()
  {
    for (int i = 0; i < getComponentCount(); ++i) {
      Component c = getComponent(i);
      if (c instanceof SymbolPanel) {
        ((SymbolPanel) c).fixCornerPoints();
      }
    }
  }

  @Override
  public void setBounds(int x,
                        int y,
                        int w,
                        int h)
  {
    super.setBounds(x,
                    y,
                    w,
                    h);
    fixCornerPoints();
  }

  @Override
  public void setEnabled(boolean en)
  {
    super.setEnabled(en);
    for (int i = 0; i < getComponentCount(); ++i) {
      Component c = getComponent(i);
      c.setEnabled(en);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
   * this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    blinkTimer1 = new eu.hansolo.steelseries.tools.BlinkTimer();
    e6 = new at.or.reder.rpi.SymbolPanel();
    e8 = new at.or.reder.rpi.SymbolPanel();
    e4 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel1 = new at.or.reder.rpi.SymbolPanel();

    blinkTimer1.setRunning(true);

    setLayout(new java.awt.GridBagLayout());

    k7.setName("K7"); // NOI18N
    k7.setSymbolType(at.or.reder.rpi.model.SymbolType.F1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(k7, gridBagConstraints);

    as7.setName("AS7"); // NOI18N
    as7.setSymbolType(at.or.reder.rpi.model.SymbolType.S1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(as7, gridBagConstraints);

    w6.setEastNeighbour(g107_1);
    w6.setName("W6"); // NOI18N
    w6.setRotation(at.or.reder.rpi.model.SymbolRotation.CW180);
    w6.setSouthNeighbour(as5);
    w6.setSymbolType(at.or.reder.rpi.model.SymbolType.W1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(w6, gridBagConstraints);

    g107_1.setName("G107.1"); // NOI18N
    g107_1.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g107_1, gridBagConstraints);

    k5.setName("K5"); // NOI18N
    k5.setSymbolType(at.or.reder.rpi.model.SymbolType.F1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(k5, gridBagConstraints);

    g5_1.setName("G5.1"); // NOI18N
    g5_1.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g5_1, gridBagConstraints);

    as5.setName("AS5"); // NOI18N
    as5.setSymbolType(at.or.reder.rpi.model.SymbolType.S1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(as5, gridBagConstraints);

    g103.setName("G103"); // NOI18N
    g103.setSymbolType(at.or.reder.rpi.model.SymbolType.D2);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g103, gridBagConstraints);

    w5.setEastNeighbour(e5);
    w5.setName("W5"); // NOI18N
    w5.setSouthNeighbour(g3_2);
    w5.setSymbolType(at.or.reder.rpi.model.SymbolType.W4);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(w5, gridBagConstraints);

    g3_2.setEastNeighbour(g103);
    g3_2.setName("G3.2"); // NOI18N
    g3_2.setRotation(at.or.reder.rpi.model.SymbolRotation.CW180);
    g3_2.setSouthNeighbour(as1);
    g3_2.setSymbolType(at.or.reder.rpi.model.SymbolType.B1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g3_2, gridBagConstraints);

    as3.setName("AS3"); // NOI18N
    as3.setSymbolType(at.or.reder.rpi.model.SymbolType.S1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(as3, gridBagConstraints);

    g3_1.setName("G3.1"); // NOI18N
    g3_1.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g3_1, gridBagConstraints);

    k3.setName("K3"); // NOI18N
    k3.setSymbolType(at.or.reder.rpi.model.SymbolType.F1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(k3, gridBagConstraints);

    g107_2.setName("G107.2"); // NOI18N
    g107_2.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g107_2, gridBagConstraints);

    k1.setName("K1"); // NOI18N
    k1.setSymbolType(at.or.reder.rpi.model.SymbolType.F1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(k1, gridBagConstraints);

    g1_1.setName("G1.1"); // NOI18N
    g1_1.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g1_1, gridBagConstraints);

    g1_2.setName("G1.2"); // NOI18N
    g1_2.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g1_2, gridBagConstraints);

    as1.setName("AS1"); // NOI18N
    as1.setSymbolType(at.or.reder.rpi.model.SymbolType.S1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(as1, gridBagConstraints);

    w4.setEastNeighbour(w3);
    w4.setName("W4"); // NOI18N
    w4.setNorthNeighbour(g103);
    w4.setSouthNeighbour(as2);
    w4.setSymbolType(at.or.reder.rpi.model.SymbolType.K2);
    w4.setWestNeighbour(as1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(w4, gridBagConstraints);

    w3.setName("W3"); // NOI18N
    w3.setNorthNeighbour(e3);
    w3.setSymbolType(at.or.reder.rpi.model.SymbolType.W1);
    w3.setWestNeighbour(w4);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(w3, gridBagConstraints);

    as2.setName("AS2"); // NOI18N
    as2.setSymbolType(at.or.reder.rpi.model.SymbolType.S1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(as2, gridBagConstraints);

    g2_4.setName("G2.4"); // NOI18N
    g2_4.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g2_4, gridBagConstraints);

    g2_3.setName("G2.3"); // NOI18N
    g2_3.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g2_3, gridBagConstraints);

    g2_2.setName("G2.2"); // NOI18N
    g2_2.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g2_2, gridBagConstraints);

    g2_1.setName("G2.1"); // NOI18N
    g2_1.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g2_1, gridBagConstraints);

    w9.setName("W9"); // NOI18N
    w9.setSouthNeighbour(e6);
    w9.setSymbolType(at.or.reder.rpi.model.SymbolType.W2);
    w9.setWestNeighbour(as4);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(w9, gridBagConstraints);

    as4.setName("AS4"); // NOI18N
    as4.setSymbolType(at.or.reder.rpi.model.SymbolType.S1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(as4, gridBagConstraints);

    w10.setName("W10"); // NOI18N
    w10.setRotation(at.or.reder.rpi.model.SymbolRotation.CW180);
    w10.setSouthNeighbour(e8);
    w10.setSymbolType(at.or.reder.rpi.model.SymbolType.W3);
    w10.setWestNeighbour(g6);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(w10, gridBagConstraints);

    g6.setName("G6"); // NOI18N
    g6.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g6, gridBagConstraints);

    w8.setName("W8"); // NOI18N
    w8.setNorthNeighbour(w3);
    w8.setRotation(at.or.reder.rpi.model.SymbolRotation.CW180);
    w8.setSouthNeighbour(e4);
    w8.setSymbolType(at.or.reder.rpi.model.SymbolType.DW1);
    w8.setWestNeighbour(as2);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(w8, gridBagConstraints);

    w1.setEastNeighbour(g1_3);
    w1.setName("W1"); // NOI18N
    w1.setRotation(at.or.reder.rpi.model.SymbolRotation.CW180);
    w1.setSouthNeighbour(g2_5);
    w1.setSymbolType(at.or.reder.rpi.model.SymbolType.W1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(w1, gridBagConstraints);

    k1_1.setName("K1.1"); // NOI18N
    k1_1.setSymbolType(at.or.reder.rpi.model.SymbolType.F1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 7;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(k1_1, gridBagConstraints);

    k2.setName("K2"); // NOI18N
    k2.setSymbolType(at.or.reder.rpi.model.SymbolType.F1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 7;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(k2, gridBagConstraints);

    g4_3.setEastNeighbour(e4);
    g4_3.setName("G4.3"); // NOI18N
    g4_3.setNorthNeighbour(as2);
    g4_3.setSymbolType(at.or.reder.rpi.model.SymbolType.B2);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g4_3, gridBagConstraints);

    g2_5.setName("G2.5"); // NOI18N
    g2_5.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g2_5, gridBagConstraints);

    es1.setName("ES1"); // NOI18N
    es1.setSymbolType(at.or.reder.rpi.model.SymbolType.S2);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 10;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(es1, gridBagConstraints);

    w7.setName("W7"); // NOI18N
    w7.setNorthNeighbour(g1_3);
    w7.setSymbolType(at.or.reder.rpi.model.SymbolType.W1);
    w7.setWestNeighbour(g2_5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 9;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(w7, gridBagConstraints);

    g8_2.setEastNeighbour(e8);
    g8_2.setName("G8.2"); // NOI18N
    g8_2.setNorthNeighbour(g6);
    g8_2.setSymbolType(at.or.reder.rpi.model.SymbolType.B2);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g8_2, gridBagConstraints);

    g8_1.setName("G8.1"); // NOI18N
    g8_1.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g8_1, gridBagConstraints);

    g4_1.setName("G4.1"); // NOI18N
    g4_1.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g4_1, gridBagConstraints);

    g4_2.setName("G4.2"); // NOI18N
    g4_2.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(g4_2, gridBagConstraints);

    e5.setName("EG5"); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    add(e5, gridBagConstraints);

    e6.setName("EG6"); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    add(e6, gridBagConstraints);

    e8.setName("EG8"); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    add(e8, gridBagConstraints);

    e4.setName("EG4"); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    add(e4, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    add(e3, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    add(symbolPanel1, gridBagConstraints);

    g1_3.setName("G1.3"); // NOI18N
    g1_3.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 9;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    add(g1_3, gridBagConstraints);

    sb1.setName("SB1"); // NOI18N
    sb1.setSymbolType(at.or.reder.rpi.model.SymbolType.S1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 10;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    add(sb1, gridBagConstraints);

    fht.setBlinkTimer(blinkTimer1);
    fht.setName("FHT"); // NOI18N
    fht.setSymbolType(at.or.reder.rpi.model.SymbolType.FHT);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    add(fht, gridBagConstraints);

    hagt.setSymbolType(at.or.reder.rpi.model.SymbolType.HAGT);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 9;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    add(hagt, gridBagConstraints);

    sgt.setSymbolType(at.or.reder.rpi.model.SymbolType.SGT);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 9;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    add(sgt, gridBagConstraints);

    wgt.setBlinkTimer(blinkTimer1);
    wgt.setSymbolType(at.or.reder.rpi.model.SymbolType.WGT);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 7;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    add(wgt, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private final at.or.reder.rpi.SymbolPanel as1 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel as2 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel as3 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel as4 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel as5 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel as7 = new at.or.reder.rpi.SymbolPanel();
  private eu.hansolo.steelseries.tools.BlinkTimer blinkTimer1;
  private final at.or.reder.rpi.SymbolPanel e3 = new at.or.reder.rpi.SymbolPanel();
  private at.or.reder.rpi.SymbolPanel e4;
  private final at.or.reder.rpi.SymbolPanel e5 = new at.or.reder.rpi.SymbolPanel();
  private at.or.reder.rpi.SymbolPanel e6;
  private at.or.reder.rpi.SymbolPanel e8;
  private final at.or.reder.rpi.SymbolPanel es1 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel fht = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g103 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g107_1 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g107_2 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g1_1 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g1_2 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g1_3 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g2_1 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g2_2 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g2_3 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g2_4 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g2_5 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g3_1 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g3_2 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g4_1 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g4_2 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g4_3 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g5_1 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g6 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g8_1 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel g8_2 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel hagt = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel k1 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel k1_1 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel k2 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel k3 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel k5 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel k7 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel sb1 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel sgt = new at.or.reder.rpi.SymbolPanel();
  private at.or.reder.rpi.SymbolPanel symbolPanel1;
  private final at.or.reder.rpi.SymbolPanel w1 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel w10 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel w3 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel w4 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel w5 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel w6 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel w7 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel w8 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel w9 = new at.or.reder.rpi.SymbolPanel();
  private final at.or.reder.rpi.SymbolPanel wgt = new at.or.reder.rpi.SymbolPanel();
  // End of variables declaration//GEN-END:variables
}
