/*
 * Copyright 2019 Wolfgang Reder.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package at.or.reder.rpi;

/**
 *
 * @author Wolfgang Reder
 */
public class MarchtrenkPanel extends javax.swing.JPanel
{

  /**
   * Creates new form MarchtrenkPanel
   */
  public MarchtrenkPanel()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
   * this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    symbolPanel1 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel33 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel2 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel3 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel4 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel5 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel6 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel7 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel8 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel9 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel10 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel11 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel12 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel13 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel14 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel15 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel16 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel17 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel18 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel19 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel20 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel21 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel22 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel23 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel24 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel25 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel26 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel27 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel32 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel31 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel30 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel29 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel28 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel34 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel35 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel36 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel37 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel38 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel39 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel40 = new at.or.reder.rpi.SymbolPanel();
    symbolPanel41 = new at.or.reder.rpi.SymbolPanel();

    setLayout(new java.awt.GridBagLayout());

    symbolPanel1.setSymbolType(at.or.reder.rpi.model.SymbolType.F1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel1, gridBagConstraints);

    symbolPanel33.setSymbolType(at.or.reder.rpi.model.SymbolType.S1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel33, gridBagConstraints);

    symbolPanel2.setRotation(at.or.reder.rpi.model.SymbolRotation.CW180);
    symbolPanel2.setSymbolType(at.or.reder.rpi.model.SymbolType.W1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel2, gridBagConstraints);

    symbolPanel3.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel3, gridBagConstraints);

    symbolPanel4.setSymbolType(at.or.reder.rpi.model.SymbolType.F1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel4, gridBagConstraints);

    symbolPanel5.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel5, gridBagConstraints);

    symbolPanel6.setSymbolType(at.or.reder.rpi.model.SymbolType.S1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel6, gridBagConstraints);

    symbolPanel7.setSymbolType(at.or.reder.rpi.model.SymbolType.D2);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel7, gridBagConstraints);

    symbolPanel8.setSymbolType(at.or.reder.rpi.model.SymbolType.W4);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel8, gridBagConstraints);

    symbolPanel9.setRotation(at.or.reder.rpi.model.SymbolRotation.CW180);
    symbolPanel9.setSymbolType(at.or.reder.rpi.model.SymbolType.B1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel9, gridBagConstraints);

    symbolPanel10.setSymbolType(at.or.reder.rpi.model.SymbolType.S1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel10, gridBagConstraints);

    symbolPanel11.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel11, gridBagConstraints);

    symbolPanel12.setSymbolType(at.or.reder.rpi.model.SymbolType.F1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel12, gridBagConstraints);

    symbolPanel13.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel13, gridBagConstraints);

    symbolPanel14.setSymbolType(at.or.reder.rpi.model.SymbolType.F1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel14, gridBagConstraints);

    symbolPanel15.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel15, gridBagConstraints);

    symbolPanel16.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel16, gridBagConstraints);

    symbolPanel17.setSymbolType(at.or.reder.rpi.model.SymbolType.S1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel17, gridBagConstraints);

    symbolPanel18.setSymbolType(at.or.reder.rpi.model.SymbolType.K2);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel18, gridBagConstraints);

    symbolPanel19.setSymbolType(at.or.reder.rpi.model.SymbolType.W1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel19, gridBagConstraints);

    symbolPanel20.setSymbolType(at.or.reder.rpi.model.SymbolType.S1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel20, gridBagConstraints);

    symbolPanel21.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel21, gridBagConstraints);

    symbolPanel22.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel22, gridBagConstraints);

    symbolPanel23.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel23, gridBagConstraints);

    symbolPanel24.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel24, gridBagConstraints);

    symbolPanel25.setSymbolType(at.or.reder.rpi.model.SymbolType.W2);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel25, gridBagConstraints);

    symbolPanel26.setSymbolType(at.or.reder.rpi.model.SymbolType.S1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel26, gridBagConstraints);

    symbolPanel27.setRotation(at.or.reder.rpi.model.SymbolRotation.CW180);
    symbolPanel27.setSymbolType(at.or.reder.rpi.model.SymbolType.W3);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel27, gridBagConstraints);

    symbolPanel32.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel32, gridBagConstraints);

    symbolPanel31.setRotation(at.or.reder.rpi.model.SymbolRotation.CW180);
    symbolPanel31.setSymbolType(at.or.reder.rpi.model.SymbolType.DW1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel31, gridBagConstraints);

    symbolPanel30.setRotation(at.or.reder.rpi.model.SymbolRotation.CW180);
    symbolPanel30.setSymbolType(at.or.reder.rpi.model.SymbolType.W1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 7;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel30, gridBagConstraints);

    symbolPanel29.setSymbolType(at.or.reder.rpi.model.SymbolType.F1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel29, gridBagConstraints);

    symbolPanel28.setSymbolType(at.or.reder.rpi.model.SymbolType.F1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel28, gridBagConstraints);

    symbolPanel34.setSymbolType(at.or.reder.rpi.model.SymbolType.B2);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel34, gridBagConstraints);

    symbolPanel35.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 7;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel35, gridBagConstraints);

    symbolPanel36.setSymbolType(at.or.reder.rpi.model.SymbolType.S2);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel36, gridBagConstraints);

    symbolPanel37.setSymbolType(at.or.reder.rpi.model.SymbolType.W1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel37, gridBagConstraints);

    symbolPanel38.setSymbolType(at.or.reder.rpi.model.SymbolType.B2);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel38, gridBagConstraints);

    symbolPanel39.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel39, gridBagConstraints);

    symbolPanel40.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel40, gridBagConstraints);

    symbolPanel41.setSymbolType(at.or.reder.rpi.model.SymbolType.G1);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1428;
    gridBagConstraints.weighty = 0.1428;
    add(symbolPanel41, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private at.or.reder.rpi.SymbolPanel symbolPanel1;
  private at.or.reder.rpi.SymbolPanel symbolPanel10;
  private at.or.reder.rpi.SymbolPanel symbolPanel11;
  private at.or.reder.rpi.SymbolPanel symbolPanel12;
  private at.or.reder.rpi.SymbolPanel symbolPanel13;
  private at.or.reder.rpi.SymbolPanel symbolPanel14;
  private at.or.reder.rpi.SymbolPanel symbolPanel15;
  private at.or.reder.rpi.SymbolPanel symbolPanel16;
  private at.or.reder.rpi.SymbolPanel symbolPanel17;
  private at.or.reder.rpi.SymbolPanel symbolPanel18;
  private at.or.reder.rpi.SymbolPanel symbolPanel19;
  private at.or.reder.rpi.SymbolPanel symbolPanel2;
  private at.or.reder.rpi.SymbolPanel symbolPanel20;
  private at.or.reder.rpi.SymbolPanel symbolPanel21;
  private at.or.reder.rpi.SymbolPanel symbolPanel22;
  private at.or.reder.rpi.SymbolPanel symbolPanel23;
  private at.or.reder.rpi.SymbolPanel symbolPanel24;
  private at.or.reder.rpi.SymbolPanel symbolPanel25;
  private at.or.reder.rpi.SymbolPanel symbolPanel26;
  private at.or.reder.rpi.SymbolPanel symbolPanel27;
  private at.or.reder.rpi.SymbolPanel symbolPanel28;
  private at.or.reder.rpi.SymbolPanel symbolPanel29;
  private at.or.reder.rpi.SymbolPanel symbolPanel3;
  private at.or.reder.rpi.SymbolPanel symbolPanel30;
  private at.or.reder.rpi.SymbolPanel symbolPanel31;
  private at.or.reder.rpi.SymbolPanel symbolPanel32;
  private at.or.reder.rpi.SymbolPanel symbolPanel33;
  private at.or.reder.rpi.SymbolPanel symbolPanel34;
  private at.or.reder.rpi.SymbolPanel symbolPanel35;
  private at.or.reder.rpi.SymbolPanel symbolPanel36;
  private at.or.reder.rpi.SymbolPanel symbolPanel37;
  private at.or.reder.rpi.SymbolPanel symbolPanel38;
  private at.or.reder.rpi.SymbolPanel symbolPanel39;
  private at.or.reder.rpi.SymbolPanel symbolPanel4;
  private at.or.reder.rpi.SymbolPanel symbolPanel40;
  private at.or.reder.rpi.SymbolPanel symbolPanel41;
  private at.or.reder.rpi.SymbolPanel symbolPanel5;
  private at.or.reder.rpi.SymbolPanel symbolPanel6;
  private at.or.reder.rpi.SymbolPanel symbolPanel7;
  private at.or.reder.rpi.SymbolPanel symbolPanel8;
  private at.or.reder.rpi.SymbolPanel symbolPanel9;
  // End of variables declaration//GEN-END:variables
}
