/*
 * Copyright 2020 Wolfgang Reder.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package at.or.reder.tools.fieldtest;

import java.util.Set;
import java.util.concurrent.CopyOnWriteArraySet;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Wolfgang Reder
 */
public class LedPanel extends javax.swing.JPanel
{

  private final Set<ChangeListener> changeListener = new CopyOnWriteArraySet<>();

  /**
   * Creates new form LedPanel
   */
  public LedPanel()
  {
    initComponents();
  }

  public int getValue()
  {
    int value = 0;
    if (ck1.isSelected()) {
      value |= 0x01;
    }
    if (ck2.isSelected()) {
      value |= 0x02;
    }
    if (ck3.isSelected()) {
      value |= 0x04;
    }
    if (ck4.isSelected()) {
      value |= 0x08;
    }
    if (ck5.isSelected()) {
      value |= 0x10;
    }
    if (ck6.isSelected()) {
      value |= 0x20;
    }
    if (ck8.isSelected()) {
      value |= 0x40;
    }
    if (ck9.isSelected()) {
      value |= 0x80;
    }
    return value;
  }

  public void setValue(int v)
  {
    ck1.setSelected((v & 0x01) != 0);
    ck2.setSelected((v & 0x02) != 0);
    ck3.setSelected((v & 0x04) != 0);
    ck4.setSelected((v & 0x08) != 0);
    ck5.setSelected((v & 0x10) != 0);
    ck6.setSelected((v & 0x20) != 0);
    ck8.setSelected((v & 0x40) != 0);
    ck9.setSelected((v & 0x80) != 0);
    updateLabel(v);
  }

  private void updateLabel(int v)
  {
    jLabel2.setText("0x" + Integer.toHexString(v));
  }

  public void addChangeListener(ChangeListener l)
  {
    if (l != null) {
      changeListener.add(l);
    }
  }

  public void removeChangeListener(ChangeListener l)
  {
    changeListener.remove(l);
  }

  private void fireChange()
  {
    updateLabel(getValue());
    ChangeEvent evt = new ChangeEvent(this);
    for (ChangeListener l : changeListener) {
      l.stateChanged(evt);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
   * this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();

    setLayout(new java.awt.GridBagLayout());

    ck1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    ck1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        ck1ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.3333333;
    gridBagConstraints.weighty = 0.25;
    add(ck1, gridBagConstraints);

    ck2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    ck2.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        ck2ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.3333333;
    gridBagConstraints.weighty = 0.25;
    add(ck2, gridBagConstraints);

    ck3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    ck3.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        ck3ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.3333333;
    gridBagConstraints.weighty = 0.25;
    add(ck3, gridBagConstraints);

    ck4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    ck4.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        ck4ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.3333333;
    gridBagConstraints.weighty = 0.25;
    add(ck4, gridBagConstraints);

    ck9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    ck9.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        ck9ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.3333333;
    gridBagConstraints.weighty = 0.25;
    add(ck9, gridBagConstraints);

    ck5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    ck5.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        ck5ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.3333333;
    gridBagConstraints.weighty = 0.25;
    add(ck5, gridBagConstraints);

    ck6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    ck6.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        ck6ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.3333333;
    gridBagConstraints.weighty = 0.25;
    add(ck6, gridBagConstraints);

    jLabel1.setText("<html>&nbsp;"); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.3333333;
    gridBagConstraints.weighty = 0.25;
    add(jLabel1, gridBagConstraints);

    ck8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    ck8.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        ck8ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.3333333;
    gridBagConstraints.weighty = 0.25;
    add(ck8, gridBagConstraints);

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("jLabel2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    add(jLabel2, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void ck1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ck1ActionPerformed
  {//GEN-HEADEREND:event_ck1ActionPerformed
    fireChange();
  }//GEN-LAST:event_ck1ActionPerformed

  private void ck2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ck2ActionPerformed
  {//GEN-HEADEREND:event_ck2ActionPerformed
    fireChange();
  }//GEN-LAST:event_ck2ActionPerformed

  private void ck3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ck3ActionPerformed
  {//GEN-HEADEREND:event_ck3ActionPerformed
    fireChange();
  }//GEN-LAST:event_ck3ActionPerformed

  private void ck4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ck4ActionPerformed
  {//GEN-HEADEREND:event_ck4ActionPerformed
    fireChange();
  }//GEN-LAST:event_ck4ActionPerformed

  private void ck9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ck9ActionPerformed
  {//GEN-HEADEREND:event_ck9ActionPerformed
    fireChange();
  }//GEN-LAST:event_ck9ActionPerformed

  private void ck5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ck5ActionPerformed
  {//GEN-HEADEREND:event_ck5ActionPerformed
    fireChange();
  }//GEN-LAST:event_ck5ActionPerformed

  private void ck6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ck6ActionPerformed
  {//GEN-HEADEREND:event_ck6ActionPerformed
    fireChange();
  }//GEN-LAST:event_ck6ActionPerformed

  private void ck8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ck8ActionPerformed
  {//GEN-HEADEREND:event_ck8ActionPerformed
    fireChange();
  }//GEN-LAST:event_ck8ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private final javax.swing.JCheckBox ck1 = new javax.swing.JCheckBox();
  private final javax.swing.JCheckBox ck2 = new javax.swing.JCheckBox();
  private final javax.swing.JCheckBox ck3 = new javax.swing.JCheckBox();
  private final javax.swing.JCheckBox ck4 = new javax.swing.JCheckBox();
  private final javax.swing.JCheckBox ck5 = new javax.swing.JCheckBox();
  private final javax.swing.JCheckBox ck6 = new javax.swing.JCheckBox();
  private final javax.swing.JCheckBox ck8 = new javax.swing.JCheckBox();
  private final javax.swing.JCheckBox ck9 = new javax.swing.JCheckBox();
  private javax.swing.JLabel jLabel2;
  // End of variables declaration//GEN-END:variables
}
